name: Deploy Django UAT App

on:
  push:
    branches:
      - detox-uat-branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3

        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}

          script: |
            cd /home/ubuntu/detox_uat

            git checkout detox-uat-branch

            git pull origin detox-uat-branch

            docker compose up -d --build